apiVersion: v1
kind: ConfigMap
metadata:
  name: topo-config
data:
  eda.json: |
    {
      "metadata": {},
      "items": [
        {
          "metadata": {
            "namespace": "default",
            "creationTimestamp": null
          },
          "spec": {
            "nodes": [
              {
                "name": "dut1",
                "labels": {
                  "eda.nokia.com/role": "leaf"
                },
                "spec": {
                  "operatingSystem": "srl",
                  "version": "24.7.1",
                  "platform": "7220 IXR-D3L",
                  "nodeProfile": "srlinux-ghcr-24.7.1"
                }
              },
              {
                  "name": "dut2",
                  "labels": {
                    "eda.nokia.com/role": "leaf"
                  },
                  "spec": {
                    "operatingSystem": "srl",
                    "version": "24.7.1",
                    "platform": "7220 IXR-D3L",
                    "nodeProfile": "srlinux-ghcr-24.7.1"
                  }
              },
              {
                "name": "dut3",
                "labels": {
                  "eda.nokia.com/role": "spine"
                },
                "spec": {
                  "operatingSystem": "srl",
                  "version": "24.7.1",
                  "platform": "7220 IXR-D5",
                  "nodeProfile": "srlinux-ghcr-24.7.1"
                }
              }
            ],
            "links": [
              {
                "name": "dut1-dut3-1",
                "labels": {
                  "eda.nokia.com/role": "interSwitch"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut1",
                        "interfaceResource": "",
                        "interface": "ethernet-1-1"
                      },
                      "remote": {
                        "node": "dut3",
                        "interfaceResource": "",
                        "interface": "ethernet-1-1"
                      },
                      "type": "interSwitch"
                    }
                  ]
                }
              },
              {
                "name": "dut1-dut3-2",
                "labels": {
                  "eda.nokia.com/role": "interSwitch"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut1",
                        "interfaceResource": "",
                        "interface": "ethernet-1-2"
                      },
                      "remote": {
                        "node": "dut3",
                        "interfaceResource": "",
                        "interface": "ethernet-1-2"
                      },
                      "type": "interSwitch"
                    }
                  ]
                }
              },
              {
              "name": "dut2-dut3-1",
              "labels": {
                "eda.nokia.com/role": "interSwitch"
              },
              "spec": {
                "links": [
                  {
                    "local": {
                      "node": "dut2",
                      "interfaceResource": "",
                      "interface": "ethernet-1-1"
                    },
                    "remote": {
                      "node": "dut3",
                      "interfaceResource": "",
                      "interface": "ethernet-1-3"
                    },
                    "type": "interSwitch"
                  }
                ]
              }
            },
            {
              "name": "dut2-dut3-2",
              "labels": {
                "eda.nokia.com/role": "interSwitch"
              },
              "spec": {
                "links": [
                  {
                    "local": {
                      "node": "dut2",
                      "interfaceResource": "",
                      "interface": "ethernet-1-2"
                    },
                    "remote": {
                      "node": "dut3",
                      "interfaceResource": "",
                      "interface": "ethernet-1-4"
                    },
                    "type": "interSwitch"
                  }
                ]
              }
            },
            {
              "name": "dut1-ethernet-1-3",
              "encapType": "dot1q",
              "labels": {
                "eda.nokia.com/role": "edge"
              },
              "spec": {
                "links": [
                  {
                    "local": {
                      "node": "dut1",
                      "interfaceResource": "",
                      "interface": "ethernet-1-3"
                    },
                    "remote": {
                      "node": "",
                      "interfaceResource": ""
                    },
                    "type": "edge"
                  }
                ]
              }
            },
            {
                "name": "dut1-ethernet-1-4",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut1",
                        "interfaceResource": "",
                        "interface": "ethernet-1-4"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut1-ethernet-1-5",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut1",
                        "interfaceResource": "",
                        "interface": "ethernet-1-5"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut1-ethernet-1-6",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut1",
                        "interfaceResource": "",
                        "interface": "ethernet-1-6"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut1-ethernet-1-7",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut1",
                        "interfaceResource": "",
                        "interface": "ethernet-1-7"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut1-ethernet-1-8",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut1",
                        "interfaceResource": "",
                        "interface": "ethernet-1-8"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut1-ethernet-1-9",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut1",
                        "interfaceResource": "",
                        "interface": "ethernet-1-9"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
              "name": "dut1-e1011",
              "encapType": "dot1q",
              "labels": {
                "eda.nokia.com/role": "edge"
              },
              "spec": {
                "links": [
                  {
                    "local": {
                      "node": "dut1",
                      "interfaceResource": "",
                      "interface": "ethernet-1-10"
                    },
                    "remote": {
                      "node": "",
                      "interfaceResource": ""
                    },
                    "type": "edge"
                  },
                  {
                    "local": {
                      "node": "dut1",
                      "interfaceResource": "",
                      "interface": "ethernet-1-11"
                    },
                    "remote": {
                      "node": "",
                      "interfaceResource": ""
                    },
                    "type": "edge"
                  }
                ]
              }
            },
            {
                "name": "dut2-ethernet-1-3",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut2",
                        "interfaceResource": "",
                        "interface": "ethernet-1-3"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut2-ethernet-1-4",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut2",
                        "interfaceResource": "",
                        "interface": "ethernet-1-4"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut2-ethernet-1-5",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut2",
                        "interfaceResource": "",
                        "interface": "ethernet-1-5"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut2-ethernet-1-6",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut2",
                        "interfaceResource": "",
                        "interface": "ethernet-1-6"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut2-ethernet-1-7",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut2",
                        "interfaceResource": "",
                        "interface": "ethernet-1-7"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut2-ethernet-1-8",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut2",
                        "interfaceResource": "",
                        "interface": "ethernet-1-8"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
                "name": "dut2-ethernet-1-9",
                "encapType": "dot1q",
                "labels": {
                  "eda.nokia.com/role": "edge"
                },
                "spec": {
                  "links": [
                    {
                      "local": {
                        "node": "dut2",
                        "interfaceResource": "",
                        "interface": "ethernet-1-9"
                      },
                      "remote": {
                        "node": "",
                        "interfaceResource": ""
                      },
                      "type": "edge"
                    }
                  ]
                }
              },
              {
              "name": "dut2-e1011",
              "encapType": "dot1q",
              "labels": {
                "eda.nokia.com/role": "edge"
              },
              "spec": {
                "links": [
                  {
                    "local": {
                      "node": "dut2",
                      "interfaceResource": "",
                      "interface": "ethernet-1-10"
                    },
                    "remote": {
                      "node": "",
                      "interfaceResource": ""
                    },
                    "type": "edge"
                  },
                  {
                    "local": {
                      "node": "dut2",
                      "interfaceResource": "",
                      "interface": "ethernet-1-11"
                    },
                    "remote": {
                      "node": "",
                      "interfaceResource": ""
                    },
                    "type": "edge"
                  }
                ]
              }
            },
            {
              "name": "dut1-2-e1212",
              "encapType": "dot1q",
              "labels": {
                "eda.nokia.com/role": "edge"
              },
              "spec": {
                "links": [
                  {
                    "local": {
                      "node": "dut1",
                      "interfaceResource": "",
                      "interface": "ethernet-1-12"
                    },
                    "remote": {
                      "node": "",
                      "interfaceResource": ""
                    },
                    "type": "edge"
                  },
                  {
                    "local": {
                      "node": "dut2",
                      "interfaceResource": "",
                      "interface": "ethernet-1-12"
                    },
                    "remote": {
                      "node": "",
                      "interfaceResource": ""
                    },
                    "type": "edge"
                  }
                ]
              }
            }
            ]
          },
          "status": {}
        }
      ]
    }
